// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxwthkhtnqjvckukvwqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4d3Roa2h0bnFqdmNrdWt2d3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzE2MjQsImV4cCI6MjA2NTU0NzYyNH0.mDnxcns9LgIlB7_lYxRFtnUKkyUuWoEa72VqOHgbTPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);